comandi_cnc = {
    # G-codes #torni
    "G00": "Movimento rapido",
    "G0": "Movimento rapido",
    "G01": "Movimento lineare",
    "G1": "Movimento lineare",
    "G02": "Interpolazione circolare oraria",
    "G2": "Interpolazione circolare oraria",
    "G03": "Interpolazione circolare antioraria",
    "G3": "Interpolazione circolare antioraria",
    "G04": "Pausa programma",
    "G4": "Pausa programma",
    "G28": "Ritorna al punto d’origine degli assi",
    "G90" :"Usa coordinate assolute",
    "G91": "Usa coordinate relative",
    "G96": "Velocità costante del mandrino",
    "G97": "Velocità costante del mandrino con RPM",
    "G98": "Avanzamento barra caricatore millimetri/minuto",
    "G99": "Annulla G98 per tornare a lavorare in millimetri/giro",
    
    # M-codes for spindle control
    "M03": "Accendi mandrino in senso orario",
    "M3": "Accendi mandrino in senso orario",
    "M04": "Accendi mandrino in senso antiorario",
    "M4": "Accendi mandrino in senso antiorario",
    "M05": "Spegni mandrino",
    "M5": "Spegni mandrino",
    "M07": "Accendi acqua uscita dall'utensile",
    "M7": "Accendi acqua uscita dall'utensile",
    "M08": "Accendi acqua",
    "M8": "Accendi acqua",
    "M09": "Spegni acqua",
    "M9": "Spegni acqua",
    "M28": "Apertura Serrapinza/Autocentrante",
    "M29": "Chiusura Serrapinza/Autocentrante",
    "M40": "Alza il braccetto prendi pezzo",
    "M41": "Abbassa il braccetto prendi pezzo",
    "M43": "Apertura portellone",
    "M98": "Chiamata di sotto-programma",
    "M99": "Fine del sotto-programma",

    # Tool change commands
    "T101": "Cambia utensile 1 con correttore 01",
    "T0101": "Cambia utensile 1 con correttore 01",
    "T800": "Cambia utensile 8 con correttore 00 (annullera tutte le correzioni sulla T selezionata)",
    "T202": "Cambia utensile 2 con correttore 02",
    "T0202": "Cambia utensile 2 con correttore 02",

    # Setting parameters
    "S": "Imposta la velocità del mandrino",
    "F": "Imposta la velocità avanzamento torretta in lavorazione",
    "I": "Coordinate X del centro della circonferenza",
    "J": "Coordinate Y del centro della circonferenza",
    "X": "Coordinate X",
    "Y": "Coordinate Y",
    "Z": "Coordinate Z",
    "A": "Calcola Angolo",
    "R":"Raggio",
    "N": "Numero Blocco Programma",
}

